---
env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  jsx: true
  useJSXTextNode: true
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true
plugins:
  - jest
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-function-return-type': off
