Current = "1.0.0"

[[Files]]
  Path = "package.json"
  Prefix = "  \"version\": \""
  Postfix = "\","
  IsNumber = false

[[Files]]
  Path = "README.md"
  Prefix = "# object-utilities "
  Postfix = ""
  IsNumber = false
